<a href="https://colab.research.google.com/github/Aniketraj19/GoogleColab/blob/main/Copy_of_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
type(b)

NameError: ignored

In [ ]:
a.size

5

In [ ]:
# a.size    - attribute
# a.size()  - method 

In [ ]:
a.ndim

1

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.shape

(5,)

In [ ]:
a[1]

2

In [ ]:
a[0]

1

In [ ]:
print(a[1:3])  #slicing

[2 3]


In [ ]:
a[3:]

array([4, 5])

In [ ]:
a[:3]

array([1, 2, 3])

In [ ]:
print(a[1]+a[4])

7


In [ ]:
# 0D numpy array (scalar)
import numpy as np
array1 = np.array(89)
print(array1)

In [ ]:
type(array1)

In [ ]:
array1.ndim

In [ ]:
#two dimensinal numpy array
array2 = np.array([[1,2,3,4,5],[6,7,8,9,1]])
array2

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 1]])

In [ ]:
array2.ndim

In [ ]:
array2.shape

(2, 5)

In [ ]:
array3 = np.array([[[1,2,3],[4,5,6]]])
array4 = np.array([ [ [1,2,3] , [4,5,6] ] , [[1,2,3], [4,5,6]]])

In [ ]:
array3

array([[[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
array4

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
array3.ndim
array4.ndim

3

In [ ]:
#FOR higher dimensions 
array5 = np.array([1,2,3,4], ndmin = 5 )
array5

array([[[[[1, 2, 3, 4]]]]])

In [ ]:
array5.ndim

5

In [ ]:
b = np.array([4.5,8.2,1.6,5.8,3.9])
b

array([4.5, 8.2, 1.6, 5.8, 3.9])

In [ ]:
b.ndim

In [ ]:
sorted_array = np.sort(b)

In [ ]:
reverse = sorted_array[::-1]
reverse
#first : chooses elements in reverse order from array
#second : works normally (slicing)
# -1 means choose all elements in reverse order backwards

array([8.2, 5.8, 4.5, 3.9, 1.6])

In [ ]:
b[0:5:2] #printing alternative 

array([4.5, 1.6, 3.9])

In [ ]:
b = np.array([[9.0,8.0,7.0,6.0,5.0],[4.0,3.0,2.0,1.0,0.0]])
b

array([[9., 8., 7., 6., 5.],
       [4., 3., 2., 1., 0.]])

In [ ]:
b.dtype

dtype('float64')

In [ ]:
b.sort()
b

In [ ]:
np.sort(b)

In [ ]:
c = np.array(['aaa','bbb','ccccc'])
c

array(['aaa', 'bbb', 'ccccc'], dtype='<U5')

In [ ]:
c.dtype # 3 character unicode string 

dtype('<U5')

In [ ]:
#ones and zeros
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones([3,3])

In [ ]:
np.zeros([5,5], dtype = 'int64')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
# # 0 - 1 ( 0 to 255)
# RED - (255,0,0)
# GREEN - (0,255,0)
# BLUE - (0,0,255)

# CYAN - (0,255,255)
# MAGENTA - (255,0,255)
# YELLOW - (255,255,0)
# BLACK - (0,0,0)
# WHITE - (255,255,255)

# RGB - red green blue  (PRIMARY)
# CMYK - cyan magenta yellow black (SECONDARY) 
# HSV - hue saturation value
# HSL - hue saturation luminescene

In [ ]:
import numpy as np

In [ ]:
#np.arange
#np.linspace

In [ ]:
a = np.arange(10)#only the stp range is given
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a = np.arange(0,10) # start and stop range is given
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a = np.arange(0,10,2)#start stop and step is given
a

array([0, 2, 4, 6, 8])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a = np.arange(0,100,5)
a

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [ ]:
#linspace - returns evenly spaced numbers over a specified intetrval
b = np.linspace(0,10) #prints equal spaces values fro 0 to 10
b

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [ ]:
b = np.linspace(3,20,4) #prints equal spaces values fro 0 to 10
b

array([ 3.        ,  8.66666667, 14.33333333, 20.        ])

In [ ]:

b = np.linspace(0,10,15) #prints equal spaces values fro 0 to 10
b

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [ ]:
a = [1,2,3,4,5]
b = [5,1,4,7,3]
a+b

[1, 2, 3, 4, 5, 5, 1, 4, 7, 3]

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([5,1,4,7,3])

In [ ]:
x1 = a+b
x2=a-b
x3 = a*b
x4 = a/b 

In [ ]:
print(x1)

print(x2)
print(x3)
print(x4)


[ 6  3  7 11  8]
[-4  1 -1 -3  2]
[ 5  2 12 28 15]
[0.2        2.         0.75       0.57142857 1.66666667]


In [ ]:
np.sum(a)

15

In [ ]:
np.max(a)

5

In [ ]:
np.min(a)

1

In [ ]:
np.mean(a)

3.0

In [ ]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [ ]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [ ]:
np.power(a,3)

array([  1,   8,  27,  64, 125])

In [ ]:
np.sort(b)

array([1, 3, 4, 5, 7])

In [ ]:
np.unique(a)

array([1, 2, 3, 4, 5])

In [ ]:
b = np.array([[36,51,51,71,25],[2,2,14,29,23,64]])
print(b)

[list([36, 51, 51, 71, 25]) list([2, 2, 14, 29, 23, 64])]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


In [ ]:
x=np.unique(b)

In [ ]:
x

array([list([2, 2, 14, 29, 23, 64]), list([36, 51, 51, 71, 25])],
      dtype=object)

In [ ]:
from random import randint

In [ ]:
random.randint(20,40)

29

In [ ]:
import numpy as np

In [ ]:
np.random.seed(0)#saves the random values
random1 = np.random.randint(0,100,5)
random1

array([44, 47, 64, 67, 67])

In [ ]:
np.argmin(a)#returns index of the smallest valule

0

In [ ]:
np.argmax( a )#returns index of the largest value

4